name: IslandPlots
main: kabbage.islandplots.IslandPlots
author: kabbage
version: 0.1
depend: [Multiverse-Core, redProtect]
load: STARTUP
commands:
    island:
        description: The plugins basic command.
        permissions:
        usage: /is new|home|addmember|removemember|list|info|abandon|setworld|makepermanent
        aliases: [is]