name: IslandPlots
main: kabbage.islandplots.IslandPlots
author: kabbage
version: 0.1
depend: [Multiverse-Core, redProtect]
commands:
    island:
        description: The plugins basic command.
        permissions:
        usage: Nope
        aliases: [is]